# Netlify Configuration
# Deploy to: https://app.netlify.com/drop

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Headers for better performance
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/planforge-*.html"
  [headers.values]
    Cache-Control = "public, max-age=86400"
